---
clusterName: cluster-01

talosVersion: v1.3.2
kubernetesVersion: 1.26.0
endpoint: "https://cluster-01.trentscholl.com:6443"

cniConfig:
  name: none

additionalApiServerCertSans:
  - ${clusterEndpointIP}

additionalMachineCertSans:
  - ${clusterEndpointIP}
  - cluster-01.trentscholl.com

nodes:
  - hostname: k8s-node-01.trentscholl.com
    ipAddress: 10.0.10.86
    controlPlane: true
    installDisk: /dev/sda

controlPlane:
  patches:
    - |-
      cluster:
        allowSchedulingOnMasters: true
        apiServer:
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
            oidc-client-id: ${oidcClientId}
            oidc-groups-claim: https://grevillea/groups
            oidc-groups-prefix: 'oidc:'
            oidc-issuer-url: ${oidcIssuerURL}
            oidc-username-claim: email
            oidc-username-prefix: 'oidc:'
        controllerManager:
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
        discovery:
          registries:
            service:
              disabled: true
        proxy:
          disabled: true
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
        scheduler:
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
        extraManifests:
          - https://raw.githubusercontent.com/TrentScholl/home-ops/main/infrastructure/talos/rbac/oidc.yaml
      machine:
        files:
          - content: |
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true
            path: /etc/cri/conf.d/20-customization.part
            op: create
        kubelet:
          extraArgs:
            feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
            rotate-server-certificates: "true"
        install:
          extraKernelArgs:
            - "talos.logging.kernel=udp://vector.trentscholl.com:6050/"
        logging:
          destinations:
            - endpoint: "udp://vector.trentscholl.com:6051/"
              format: json_lines
        network:
          extraHostEntries:
            - ip: ${clusterEndpointIP}
              aliases:
                - cluster-01.trentscholl.com
        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"
        time:
          disabled: false
          servers:
            - time.cloudflare.com
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl