clusterEndpointIP: ENC[AES256_GCM,data:jzItUbJb5KNoPw==,iv:NPUf8uWe/Lk/1JBec59dTW8Gn/7VW/Z1fR3PuBNddi0=,tag:U0AJYME/Y2WK2rIrqB+r4A==,type:str]
oidcClientId: ENC[AES256_GCM,data:aTzdBUn+c/RzbZf7c/dFPtEAYaniRYzBRml5nPB+Qog=,iv:3Az+Yj61P+Aiqs5lk5Zfw4IcsfZMH3f2WPZqYM96728=,tag:YZXY8GG5LmzDHoLUYLZK0Q==,type:str]
oidcIssuerURL: ENC[AES256_GCM,data:U0Jm/CjFx3W8vVFQi6aiuYRLJYOucVlBB5hdTXFjXw==,iv:rU+ixUxiqBaGjfE4mqu6L9k6cB5O+bG4wyNn6+lg+wY=,tag:Vwcfq34cNFNny4L3R8fTaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1efzlapsuahun6sg22yhvpmz0dwx58m0mqxtc2xstemvh6qtgvpdslh5yur
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWXJ5WkRGM0ZGWkFaZlJZ
            R0drSWQxNm5CNGtrYncyMGh4TTJwY0w2WWhFCjlkQjFZRG1UMUlJSUl0ZjZiMXUw
            Z2lCeTVTMllDc002MGFpRlZZZ1NOazgKLS0tIGlqRkpQZVFSNVFEYzQ1WVR2RlZ0
            VXBkSGtBZkxKYUdtYmlFbWY1Q0IxcFEKeo6HJvmDmF3hu/MiZK0rwg2sDzyHTFv6
            UN9ztJzswRApY12NzBCKajsmfOQDyVhSC396aUp7NeL/uwn5NzUVdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-17T06:27:03Z"
    mac: ENC[AES256_GCM,data:cLjpb5eakf3hPK31APyvG2oUWEJXBk7r63/lFXsoy62Tplld5xOyiouOwbv6Uze1gdRjfibKChEDDBRoA8CFnJYH4dCeLyhmsee4QvCYMjwkYD4BAZweR9kUEALjo1R68+c/fd6BIcGoW1FZO0Msr+jkZTO8bIJPt4uev3UTMgU=,iv:fmEj0cVTWjGZfndTsGIRZzBvWKEMwnROQKc1/RKwBxo=,tag:1xXetgiFnQsqr8dNQ+QYcA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
