---
# yaml-language-server: $schema=https://kubernetes-schemas.trentscholl.com/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-ddns-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cloudflare
