---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1efzlapsuahun6sg22yhvpmz0dwx58m0mqxtc2xstemvh6qtgvpdslh5yur
  - path_regex: kubernetes/.*\.sops\.ini
    key_groups:
      - age:
          - age1efzlapsuahun6sg22yhvpmz0dwx58m0mqxtc2xstemvh6qtgvpdslh5yur
  - path_regex: kubernetes/.*\.sops\.toml
    key_groups:
      - age:
          - age1efzlapsuahun6sg22yhvpmz0dwx58m0mqxtc2xstemvh6qtgvpdslh5yur
  - path_regex: kubernetes/.*\.sops\.json
    key_groups:
      - age:
          - age1efzlapsuahun6sg22yhvpmz0dwx58m0mqxtc2xstemvh6qtgvpdslh5yur
  - path_regex: infrastructure/talos/.*\.sops\.ya?ml
    age: >-
      age1efzlapsuahun6sg22yhvpmz0dwx58m0mqxtc2xstemvh6qtgvpdslh5yur