---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./esphome/ks.yaml
  - ./home-assistant/ks.yaml
  - ./mealie/ks.yaml
  - ./minio/ks.yaml
  - ./overseerr/ks.yaml
  - ./plex/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./recyclarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./zigbee2mqtt/ks.yaml
  - ./zwave/ks.yaml
