---
# yaml-language-server: $schema=https://kubernetes-schemas.trentscholl.com/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: democratic-csi
  namespace: flux-system
spec:
  interval: 2h
  url: https://democratic-csi.github.io/charts
