---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-sigs-metrics-server.yaml
  - cilium.yaml  
  - ./actions-runner-controller.yaml
  - ./angelnu.yaml
  - ./aqua.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./calico.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./csi-driver-nfs.yaml
  - ./democratic-csi.yaml
  - ./descheduler.yaml
  - ./emqx.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./fairwinds.yaml
  - ./falco-security.yaml
  - ./gitea.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./kubernetes-dashboard.yaml
  - ./kyverno.yaml
  - ./metrics-server.yaml
  - ./nextcloud.yaml
  - ./node-feature-discovery.yaml
  - ./piraeus.yaml
  - ./prometheus-community.yaml
  - ./redis-operator.yaml
  - ./stakater.yaml
  - ./tf-controller.yaml
  - ./weaveworks.yaml
