---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zwave-js-ui
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: proxmox-csi-plugin
      namespace: storage
    - name: volsync
      namespace: storage
  values:
    controllers:
      zwave-js-ui:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/zwave-js/zwave-js-ui
              tag: 9.16.2@sha256:5a9fefa1a7c334137dabc389f714bacfce7b874d5e3bb045beef6bd8c29162e2
            env:
              TZ: Australia/Brisbane
              PORT: &port 80
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    defaultPodOptions:
      nodeSelector:
        aeotec.feature.node.kubernetes.io/zwave: "true"
    service:
      app:
        controller: zwave-js-ui
        ports:
          http:
            port: *port
          websocket:
            port: 3000
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.trentscholl.com
        className: internal
        hosts:
          - host: "zwave.trentscholl.com"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: zwave-js-ui
        globalMounts:
          - path: /usr/src/app/store
      tmp:
        type: emptyDir
      usb:
        type: hostPath
        hostPath: /dev/serial/by-id/usb-0658_0200-if00
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/serial/by-id/usb-0658_0200-if00
