---
apiVersion: v1
kind: Service
metadata:
  name: &app postgres-lb
  namespace: default
  annotations:
    coredns.io/hostname: postgres.trentscholl.com
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadbalancerIP: "${SVC_POSTGRES_ADDR}"
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    postgresql: postgres
    role: primary
