---
# yaml-language-server: $schema=https://kubernetes-schemas.trentscholl.com/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        PUSHOVER_TOKEN: "{{ .PUSHOVER_TOKEN }}"
  dataFrom:
    - extract:
        key: radarr
    - extract:
        key: pushover
