---
# yaml-language-server: $schema=https://kubernetes-schemas.trentscholl.com/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: me@trentscholl.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: me@trentscholl.com
            apiKeySecretRef:
              name: cloudflare-secret
              key: CLOUDFLARE_APIKEY
        selector:
          dnsZones:
            - trentscholl.com
---
# yaml-language-server: $schema=https://kubernetes-schemas.trentscholl.com/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: me@trentscholl.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: me@trentscholl.com
            apiKeySecretRef:
              name: cloudflare-secret
              key: CLOUDFLARE_APIKEY
        selector:
          dnsZones:
            - trentscholl.com
