---
# yaml-language-server: $schema=https://kubernetes-schemas.trentscholl.com/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-bedrock
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: itzg/minecraft-bedrock-server
      tag: latest

    env:
      EULA: "TRUE"
      VERSION: "LATEST"
      DIFFICULTY: "normal"
      SERVER_NAME: "Grevillea"
      WHITE_LIST: ""
      WHITE_LIST_USERS: ""
      OPS: "2535452917969979"
      MEMBERS: ""
      VISITORS: ""
      ALLOW_CHEATS: "false"
      MAX_PLAYERS: "5"
      VIEW_DISTANCE: "10"
      TICK_DISTANCE: "4"
      PLAYER_IDLE_TIMEOUT: "30"
      MAX_THREADS: "8"
      GAMEMODE: "survival"
      LEVEL_TYPE: "DEFAULT"
      LEVEL_NAME: "Grevillea"
      LEVEL_SEED: "-4361528937055201680"
      DEFAULT_PLAYER_PERMISSION_LEVEL: "member"
      TEXTUREPACK_REQUIRED: "false"
      ONLINE_MODE: "true"
      EMIT_SERVER_TELEMETRY: "false"
      ENABLE_LAN_VISIBILITY: "true"

    service:
      main:
        type: LoadBalancer
        externalIPs: ["${SVC_MINECRAFT_BEDROCK_ADDR}"]
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: false
          minecraft:
            enabled: true
            port: 19132
            protocol: UDP

    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          exec:
              command:
                - mc-monitor
                - status-bedrock
                - --host
                - 127.0.0.1
          initialDelaySeconds: 30
      readiness: *probes
      startup:
        enabled: false

    volumeClaimTemplates:
      - name: data
        mountPath: /data
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: truenas-iscsi-csi

    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        memory: 4000Mi
