---
# yaml-language-server: $schema=https://kubernetes-schemas.trentscholl.com/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: democratic-csi
      version: 0.13.5
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    csiDriver:
      name: "org.democratic-csi.iscsi"
    storageClasses:
    - name: truenas-iscsi-csi
      defaultClass: false
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: ext4
      mountOptions: []
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:
    driver:
      config:
        driver: freenas-api-iscsi
        instance_id:
        httpConnection:
          protocol: https
          host: nas.trentscholl.com
          apiKey:
        zfs:
          datasetProperties:
            "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          datasetParentName: data/k8s/v
          detachedSnapshotsDatasetParentName: data/k8s/s
          zvolCompression:
          zvolDedup:
          zvolEnableReservation: false
          zvolBlocksize:
        iscsi:
          targetPortal: "nas.trentscholl.com:3260"
          targetPortals: []
          interface:
          namePrefix: csi-
          nameSuffix: "-cluster"
          targetGroups:
          - targetGroupPortalGroup: 1
            targetGroupInitiatorGroup: 1
            targetGroupAuthType: None
            targetGroupAuthGroup:
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          extentBlocksize: 4096
          extentRpm: "SSD"
          extentAvailThreshold: 0
