---
kubernetes:
  children:
    master:
      vars:
        ansible_user: trentscholl
        ansible_ssh_port: 22
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      hosts:
        k8s-01:
          ansible_host: 10.1.1.21
        k8s-02:
          ansible_host: 10.1.1.22
        k8s-03:
          ansible_host: 10.1.1.23
    worker:
      vars:
        ansible_user: trentscholl
        ansible_ssh_port: 22
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      hosts:
        k8s-04:
          ansible_host: 10.1.1.24
        k8s-05:
          ansible_host: 10.1.1.25
