---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./authelia/ks.yaml
  - ./cloudnative-pg/ks.yaml
  - ./emqx/ks.yaml
  - ./glauth/ks.yaml
  - ./hajimari/ks.yaml
  - ./home-assistant/ks.yaml
  - ./kubernetes-schemas/ks.yaml
  - ./plex/ks.yaml
  - ./zwave-js-ui/ks.yaml
