apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  CLUSTER_SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:hdtqmDRy+BljearcDjaZ/Hiswn6ecvtzkw3cW2pbpTc=,iv:K8o+XEfHnVtBfMfiidoLjcRqhq1osaE5tcTI1ASj3ps=,tag:XmF+VZoiag1FIreAvj2ZGg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1efzlapsuahun6sg22yhvpmz0dwx58m0mqxtc2xstemvh6qtgvpdslh5yur
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocnJyVmpIcVUwSkhxeWs0
        b2JoZUlKTSt0VUN5R1lGTXJ2SGdxei9GOVdNCnhKbS8wWE5tQXFvVGFIa1U1dUhP
        M1hhbVRGN05JU2YvNTFzTkxMUnpNWFkKLS0tIG16enJUVk5VQ0lnMlhUV0Q2SXV5
        dldFYWZRQ1FHb2M2OVRmWXphcm5xVzAKEUtfBR9FdbPL4Q49IbLWjE4qf0A+6Qpy
        /j++NSGt6GzbdABVQB9gKjV2WHsdqRFq3cBkJhCwE5czP6AHWFVYQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-07-28T11:13:40Z"
  mac: ENC[AES256_GCM,data:gx6I3gtMRWjQ9I7Te04aJGdgrGttNRKOcKNwyNoljtxKI2QI/azR8I6xr8Efg0CzaLIZgoBSnDxmNTX15MyxbJygCcT5+cVtkG5gRV91jsHHLGUQ03p7gyC7PyU/n/WC7WFEUS4Xny47WJh/nEfUDa6ntZto2pn5UBLw/OMd0w8=,iv:Jb1hED+tRu1FBQIxaHL0N927t6XhtDKcs+5vuTFynV4=,tag:/2AjQ2Ol2PkSFycMGnPiIw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.0
