---
originRequest:
  originServerName: external.trentscholl.com

ingress:
  - hostname: trentscholl.com
    service: https://nginx-external-controller.network.svc.cluster.local:443
  - hostname: "*.trentscholl.com"
    service: https://nginx-external-controller.network.svc.cluster.local:443
  - service: http_status:404
