---
originRequest:
  http2Origin: true

ingress:
  - hostname: trentscholl.com
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: external.trentscholl.com
  - hostname: "*.trentscholl.com"
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: external.trentscholl.com
  - service: http_status:404
