---
# yaml-language-server: $schema=https://kubernetes-schemas.trentscholl.com/runnerdeployment_v1alpha1.json
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: home-ops
  namespace: actions-runner-system
spec:
  template:
    spec:
      image: ghcr.io/actions/actions-runner-controller/actions-runner-dind:v2.299.1-ubuntu-22.04
      imagePullPolicy: IfNotPresent
      dockerdWithinRunnerContainer: true
      ephemeral: true
      repository: TrentScholl/home-ops
      labels: ["self-hosted"]
---
# yaml-language-server: $schema=https://kubernetes-schemas.trentscholl.com/horizontalrunnerautoscaler_v1alpha1.json
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: home-ops
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: home-ops
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      amount: 1
      duration: 30m
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames: ["home-ops"]