---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: devbu-io
  namespace: networking
spec:
  secretName: devbu-io-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: trentscholl.com
  dnsNames:
    - trentscholl.com
    - "*.trentscholl.com"
