---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-csi-plugin
spec:
  interval: 30m
  chart:
    spec:
      chart: proxmox-csi-plugin
      version: 0.7.0
      sourceRef:
        kind: HelmRepository
        name: sergelogvinov
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    config:
      clusters:
        - url: https://vm.trentscholl.com:8006/api2/json
          insecure: false
          token_id: "kubernetes-csi@pve!csi"
          token_secret: "1f0a94ef-b62e-4489-a644-0df9f3eb3c3c"
          region: vm-cluster-01
    storageClass:
      - name: proxmox-data-nvme-xfs
        storage: data-nvme
        reclaimPolicy: Delete
        fstype: xfs
        cache: none
        ssd: true
