---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: mosquitto
      namespace: default
    - name: proxmox-csi-plugin
      namespace: storage
    - name: volsync
      namespace: storage
  values:
    controllers:
      zigbee2mqtt:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 1.36.0@sha256:4de1ee53d67a9b4556045c34a2722bfd2348dabbefcb792e862643104d3e9fd0
            env:
              TZ: Australia/Brisbane
              ZIGBEE2MQTT_DATA: /config
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: debug
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
              ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: &port 80
              ZIGBEE2MQTT_CONFIG_FRONTEND: "false"
              ZIGBEE2MQTT_CONFIG_FRONTEND_URL: https://zigbee.trentscholl.com
              ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: "ezsp"
            envFrom:
              - secretRef:
                  name: zigbee2mqtt-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
        pod:
          nodeSelector:
            sonoff.feature.node.kubernetes.io/zigbee: "true"
    service:
      app:
        controller: zigbee2mqtt
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        hosts:
          - host: &host zigbee.trentscholl.com
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]
    persistence:
      config:
        existingClaim: zigbee2mqtt
      usb:
        type: hostPath
        hostPath: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20221129160505-if00
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/ttyACM0