---
# yaml-language-server: $schema=https://kubernetes-schemas.trentscholl.com/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-snmp-exporter-eaton-ups
  namespace: flux-system
spec:
  path: ./kubernetes/apps/monitoring/snmp-exporter/eaton-ups
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: snmp-exporter-eaton-ups
      namespace: monitoring
  interval: 30m
  retryInterval: 1m
  timeout: 3m
