---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trentscholl-com
spec:
  secretName: trentscholl-com
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: trentscholl.com
  dnsNames:
    - trentscholl.com
    - "*.trentscholl.com"
