{
 "title": "Eaton UPS 5P 1550",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Device",
    "query": {
     "query": "label_values(upsIdentName,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Output Load",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "upsOutputPercentLoad{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Output Power",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upsOutputPower{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Battery Capacity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "0.1*upsHighPrecBatteryCapacity{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Run Time Remaining",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upsEstimatedMinutesRemaining{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Time on Battery",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "upsSecondsOnBattery{instance=\"$instance\"}/60/100"
    }
   ]
  },
  {
   "title": "Battery Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upsBatteryTemperature{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "upsInputVoltage{instance=\"$instance\"}",
     "legendFormat": "Line Input"
    },
    {
     "expr": "upsOutputVoltage{instance=\"$instance\"}",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "0.1*upsInputFrequency{instance=\"$instance\"}",
     "legendFormat": "Input"
    },
    {
     "expr": "0.1*upsOutputFrequency{instance=\"$instance\"}",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Output Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "upsOutputCurrent{instance=\"$instance\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "upsBatteryVoltage{instance=\"$instance\"}",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "Battery Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "upsBatteryCurrent{instance=\"$instance\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Total DC Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "upsOutputCurrent{instance=\"$instance\"}",
     "legendFormat": "Current"
    }
   ]
  }
 ]
}