---
# yaml-language-server: $schema=https://kubernetes-schemas.trentscholl.com/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-democratic-csi
  namespace: flux-system
  labels:
spec:
  path: ./kubernetes/apps/kube-system/democratic-csi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
