# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: kube-system
stringData:
    token: ENC[AES256_GCM,data:5U0I+CXQPQGQ6vLIts+yGig9SEjB7rikv61MjbfeWELKf2mxZhW1d3NVqJmtP7AV9xvhL4vXFpPYWG4iiks2DcZxUjv9dXZLawrMKIVqUO26uZ7q/zk/wNKqSsU9D7F6UMb8TL88qY5VDtZGbzUoraA1wpLWIe+eDdCEaiO0OT7UrkjLNyWbFYv04Ek18u3LnoviWhfYQrdG71Sr2KaTvu82sefHWr8HDh+ehEj4ttHM4X6rrdGgtiLDRS+aA7CqmvsZbfwY680oQt3JnK+B7+EkZLVyHYwnuQI2iKzKwnwTg74Db+QyaTxt6LbOmfyjN4TyzojxVeow4MeSz2w0eWkxN17cvx36ELtNDTjjapaTsEg7PUhvYWXnzYah9oiRbuD7rQjcgquxQmltlncmsKU1/Hwuoks2MQDdg2ImeCOmLsqG7SweSaLeaD6KyBAMzXOf7x4ID1oeAB9/1E4ETgTOMfVee/Dg5ltnvd3gnE1bynIkOxS8FC9oRXa5eOWdER8P2Cn2wvgOeyIawVrcqyrLAEixVrYQeD0SPgjpKFFqk1sibbrPaGtcThvRcli+Kl5W59y9+WniTssWdF/oOONczNz99EaGUR275cZsil61qbNGwu9ig4zHlImh6tij6QtL4bZiFT4asxXdYLX+cxi79O0BUqeVtf8FYeGWDeINOHTrqkeQADh/WmNv9iJjjFuzxTNkdfi7pZT5dmRUmOhXBKg7i2kCsL7Ouq3BPM491wi0DfuTMcf0A6iCpyjUVdgSWVzleDERL8oujTXjqQUk2eQLWqT3DqoDK61Pbc1l/uEsq4+5hOhHEe5o3dW2l5XkKNdIdD82hs7YFpmV4IOY,iv:NvB7Ygt2BEeRrril6y7IyFqp1D14MKfl8QMNvUdZ3nk=,tag:C+mPqnF/gu1KlbfzA3N76w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1efzlapsuahun6sg22yhvpmz0dwx58m0mqxtc2xstemvh6qtgvpdslh5yur
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVXVNRnVlNWIzbitPQkZ4
            V0RsSVRqM3lITDZ6TXpsZzJ5alByZUVlYVdJCmdFQTJYSGxHTHlSdi9yOXRYelY2
            NmE4bVFVTTZYbGlzTGYvYm1HZTBUUjgKLS0tIGdPVW9kd0Q5a01vVEd4Qmg0YUIz
            QW92SG9kdVFVVW9LRFBTY0R6a3RHZGcKzpAL1aROcCiZPe4grsmGgRtZ0cZYUJW5
            5G69ETNAYwN2lktHozmgBZy0WU9FEs+Zk91hRS2nxQ8zRJ+TG+Bu0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-23T07:07:08Z"
    mac: ENC[AES256_GCM,data:grKbwI/LsbpGeoVE3sODTGT5dDhIWRtLmMW/P/EgyTHvA7Hjovc126J/nfC62ku1yLlu/Jo8tQvYdhUjRKL1Gl3aD+7rCT+GxmSc79hXrKZtZwte6PkLFNfOA0StCdjJDD9imYio+gFLuau/bd5xDnuH4qWiDGYCBy3WrOpL8bA=,iv:s9galruGH8wy2pj4XJtxvLJGGWivicd3PPDOGvFzCBg=,tag:RK/EGhIbfq95jB5IjoR3IA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3