---
timezone: Australia/Brisbane
public_ssh_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCWhB+pzNQJnGSRHNOWQFg+LnU0SX81UKnd4VkwTxPPUg8Oh0G9d3b7Hw67Nfe3YFeqNoHCpWRobk2VNN4v8Whl/JyijulxX0HfMQnX7EEfxFmfyqQyLb8Ek0w3ONO/8QB63AGFtx0BmO2XILZQujiaVBg2QVNMf6Hi2j2a1iW9LyfVioTSDelvoOPnlkiK1jqJiOTtR7NQO/VRh49QpqcJjLuyH39DXetquOey8d26964NailJzXuxLCz4LwMd8dWo3v57ML4U3soYdRXPPoOWmPTjohxA5+wYgcEjM6hiYC1PzGz5JKkhkKH2BS4ga/18mLbMjQoVUQsGM2cHO+5Sg2pvI2APFnjkp54SYQrVeOnv8pWdnbQdQDocd6sA83B3Pv8xHKPYGt1B5Ji2V1vtwA/PeIncQKYGhYYJs7PHFgBAIjLFAH6QU9nDw4/hMnedyo+wbMynZk8BCsFjNS4sLEOSRKF358AokwEHeAm28XsHG+Y8IvsMbd8/pxCuDQc= trent"
packages_repositories:
  - ppa:fish-shell/release-3
packages_install:
  - apt-transport-https
  - arptables
  - ca-certificates
  - curl
  - ebtables
  - fish
  - fzf
  - gdisk
  - hdparm
  - htop
  - iputils-ping
  - ipvsadm
  - lm-sensors
  - lvm2
  - nano
  - net-tools
  - nfs-common
  - ntpdate
  - nvme-cli
  - open-iscsi
  - psmisc
  - python3-kubernetes
  - python3-yaml
  - smartmontools
  - socat
  - software-properties-common
  - unzip
  - open-vm-tools
  - cifs-utils
  - lsscsi
  - sg3-utils
  - multipath-tools
  - scsitools
packages_remove:
  - apparmor
  - ufw
