---
# yaml-language-server: $schema=https://kubernetes-schemas.trentscholl.com/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controller:
      type: statefulset

    image:
      repository: jacobalberty/unifi
      tag: v7.4.156

    env:
      RUNAS_UID0: "false"
      UNIFI_UID: "999"
      UNIFI_GID: "999"
      UNIFI_STDOUT: "true"
      JVM_INIT_HEAP_SIZE:
      JVM_MAX_HEAP_SIZE: 1024M

    service:
      main:
        type: LoadBalancer
        externalIPs: ["${SVC_UNIFI_ADDR}"]
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8443
            protocol: HTTPS
          controller:
            enabled: true
            port: 8080
            protocol: TCP
          portal-http:
            enabled: false
            port: 8880
            protocol: HTTP
          portal-https:
            enabled: false
            port: 8843
            protocol: HTTPS
          speedtest:
            enabled: true
            port: 6789
            protocol: TCP
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          syslog:
            enabled: true
            port: 5514
            protocol: UDP
          discovery:
            enabled: true
            port: 10001
            protocol: UDP

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: &host "unifi.trentscholl.com"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    resources:
      requests:
        cpu: 23m
        memory: 1390M
      limits:
        memory: 1390M

    volumeClaimTemplates:
      - name: data
        mountPath: /unifi
        accessMode: ReadWriteOnce
        size: 2Gi
        storageClass: truenas-iscsi-csi