---
name: "Publish Docs"

on:
  push:
    branches: ["main"]
    paths: ["docs/**", "**/*.md"]
  pull_request:
    branches: ["main"]
    paths: ["docs/**", "**/*.md"]

jobs:
  publish-docs:
    name: Publish Docs
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@32691ba7c9e7063bd457bd8f2a5703138591fa58 # v1.9.0
        id: generate-token
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          token: "${{ steps.generate-token.outputs.token }}"

      - name: Build docs
        uses: docker://ghcr.io/bjw-s/mdbook:0.4.35@sha256:2365b04e892a326f139cec0e8aa4d7d5276b5c67002dcf0fbdcc2bd0382bb9eb
        with:
          args: mdbook build docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: "${{ steps.generate-token.outputs.token }}"
          publish_dir: ./docs/book
          user_name: "rosey-bot[bot]"
          user_email: "rosey-bot <98030736+rosey-bot[bot]@users.noreply.github.com>"
